### ISSUE TITLE
setting layout

### ISSUE THREAD

**Issue by vdawg-git** [eshrh/inori#5]
```toml
[keybindings]
qwerty_keybindings = true
```

Results in: 
```bash
thread 'main' panicked at src/config.rs:59:30:
  message qwerty_keybindings does not exist
       note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
What am I doing wrong?
A default config would be nice :)

And thank you for creating this, it looks quite cool

**Comment by eshrh** [comment]
sorry for the trouble, but that setting option is global, not under the keybindings table. Move that line up one and hopefully it should work. 

I need to work on the config parsing error handling, it's way too brittle right now

**Comment by vdawg-git** [comment]
All good. I get the error with it as a global setting too though 

The config:
```toml
qwerty_keybindings = true
```

Also, I don't think I want to use mpd anyway, so dont stress yourself about it :)

**Comment by eshrh** [comment]
I think you're using v0.1.0, which did qwerty/dvorak setting via a compile flag... the old docs are available on that git tag (https://github.com/eshrh/inori/tree/v0.1.0). The cargo package's [home page](https://crates.io/crates/inori) also has the instructions for installing with qwerty:

```cargo install inori --features qwerty_movement_keys --no-default-features```

(the latest arch package, pinned to v0.1.0, also has functionality in the pkgbuild to do this).


In any case, I will be pushing a new version soon that implements recent changes, which includes making dvorak/qwerty settings runtime-only, making the config file necessary in all cases.

**Comment by eshrh** [comment]
I just released a new version on cargo. The arch packaging is out of date... (to be updated at a later date, I no longer have access to an arch machine)

**Comment by vdawg-git** [comment]
Ah yes, I have the Arch pgk. I can install via cargo too to get the latest version :)
