### ISSUE TITLE
Fails to start when using the jellyfin extension with mopidy

### ISSUE THREAD

**Issue by alucryd** [eshrh/inori#7]
Hi there, looks like the jellyfin mopidy extension is preventing inori from starting:
```
Error: Server(ServerError { code: Argument, pos: 0, command: "list", detail: "Unknown tag type: albumartistsort" })
```
Might be something else, but that string is a config option in the jellyfin extension.

**Comment by eshrh** [comment]
Hi, sorry for the late response.

I'm not familiar with jellyfin, mopidy, or mopidy-MPD, but I believe that they have implemented a different mpd server trying to be compliant with the protocol. "ALBUMARTISTSORT" is one of the [supported tags](https://mpd.readthedocs.io/en/latest/protocol.html#tags) in the MPD protocol, and it seems that their implementation doesn't handle it.

 In MPD, I don't think that that error message is possible without modifying the source, as albumartistsort is [included in the list of tags](https://github.com/MusicPlayerDaemon/MPD/blob/b1677bf79c437e6de937da9f82260a1d24ad6bd2/src/tag/Names.cxx#L15) that are checked. I skimmed the mopidy-mpd source, but albumartistsort seems to be absent from the [dictionary](https://github.com/mopidy/mopidy-mpd/blob/4538f0ec3f8d4a18f2e9211627f6240dc72dee2e/src/mopidy_mpd/protocol/music_db.py#L18-L35) used to lookup tag names. 

I think this is probably an upstream bug. If you do file an issue there, I would also suggest pointing out that not only do the "*sort" fields need to be added, there's some special fallback logic that needs to be implemented for the `find` command that is readily available from the MPD source.

The use of the albumartistsort field is key to the main reason I wrote this program (latin alphabet searching for non-latin alphabet tracks), so it's hardcoded.
